version: 0.2

phases:
  install:
    commands:
      - echo "Installing docker compose to run Docker compose UP"
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
      - echo  ******************************************************************************************************
  pre_build:
    commands:
      - echo Logging in to Amazon ECR ...
      - docker --version
#      - docker build -t .
      - docker image ls
   #   - $(aws ecr get-login --region eu-west-2  --no-include-email)
      - echo  ******************************************************************************************************
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image.."      
      - echo  ******************************************************************************************************
         
  post_build:
    commands:

      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - echo  ******************************************************************************************************
