version: 0.2

phases:
  pre_build:
    commands:      
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-2)    
      - echo "Logging in to Amazon ECR..."
      - echo "installing docker compose on container with Ubuntu base image acting as Build server"
 
 
