version: 0.2

phases:
  install:
    commands:
      - echo "Installing docker compose to run Docker compose UP"
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
      - echo INSTALLING ECS_CLI
      - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      - sudo chmod +x /usr/local/bin/ecs-cli
      - echo CHECKING THE ECS_CLI VERSION
      - ecs-cli --version
      - ecs-cli configure profile --profile-name dev-phish --access-key $aws_access_key_id --secret-key $aws_secret_access_key
      - ecs-cli configure --cluster dev-phish --default-launch-type EC2 --region eu-west-2 --config-name dev-phish
 #     - cat .ecs/config
      - echo  ******************************************************************************************************
  pre_build:
    commands:
      - echo Logging.. in to Amazon ECR ...
      - docker --version
 #     - ./ecs-cli compose service up
 #     - ecs-cli service ps
 #    - ecs-cli compose up -vvv
 #    - docker build .
 #    - docker image ls
 #    - $(aws ecr get-login --region eu-west-2  --no-include-email)
      - echo  ******************************************************************************************************
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image.."      
      - echo  ******************************************************************************************************
         
  post_build:
    commands:

      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - echo  ******************************************************************************************************
