version: 0.2

phases:
  install:
    commands:
      - echo Creating notification message file ...
      - echo "CODEBUILD_INITIATOR:${CODEBUILD_INITIATOR}" | tee -a sns-message.txt
      - echo "CODEBUILD_BUILD_ID:${CODEBUILD_BUILD_ID}" | tee -a sns-message.txt
      - echo "CODEBUILD_SOURCE_REPO_URL:${CODEBUILD_SOURCE_REPO_URL}" | tee -a sns-message.txt
      - echo "CODEBUILD_SOURCE_VERSION:${CODEBUILD_SOURCE_VERSION}" | tee -a sns-message.txt
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION:${CODEBUILD_RESOLVED_SOURCE_VERSION}" | tee -a sns-message.txt
      - echo "DOCKER_COMPOSE_VERSION:${DOCKER_COMPOSE_VERSION}" | tee -a sns-message.txt
      - docker-compose --version
      - echo INSTALLING ECS_CLI...
      - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      - sudo chmod +x /usr/local/bin/ecs-cli
      - echo CHECKING THE ECS_CLI VERSION
      - ecs-cli --version
      - echo CONFIGURING ECS-CLI
      - ecs-cli configure profile --profile-name dev-phish --access-key $aws_access_key_id --secret-key $aws_secret_access_key
      - ecs-cli configure --cluster dev-phish --default-launch-type EC2 --region eu-west-2 --config-name dev-phish
      - eval $(aws ecr get-login --region eu-west-2 --no-include-email)
      - aws ecr describe-repositories
      - echo  ******************************************************************************************************
  pre_build:
    commands:
      - echo Logging.. in to Amazon ECR ...
      - docker --version
  #    - ecs-cli service ps
      - echo  ******************************************************************************************************
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image.."      
      - echo  ******************************************************************************************************
         
  post_build:
    commands:

      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - echo  ******************************************************************************************************
