version: 0.2

phases:
  install:
    commands:
      - docker-compose --version
      - echo INSTALLING ECS_CLI......
      - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      - sudo chmod +x /usr/local/bin/ecs-cli
      - DATETIME=$(date +%d%m%y__%H%M)
      - echo CHECKING THE ECS_CLI VERSION
      - echo INSTALLING NODE JS 
      - sudo apt-get install nodejs
      - ecs-cli --version
      - echo CONFIGURING ECS-CLI
      - ecs-cli configure --cluster Dev-Phishtray-Pipeline --default-launch-type EC2 --region $aws_default_region --config-name Dev-Phishtray-Pipeline
      - ecs-cli configure profile --profile-name Dev-Phishtray-Pipeline --access-key $aws_access_key_id --secret-key $aws_secret_access_key

#      - ecs-cli configure profile --profile-name Dev-Phishtray-Pipeline --access-key $aws_access_key_id --secret-key $aws_secret_access_key
#      - ecs-cli configure --cluster Dev-Phishtray-Pipeline --default-launch-type EC2 --region $aws_default_region --config-name dev-phish

      - echo  ******************************************************************************************************
  
  pre_build:
    commands:
      - echo Creating notification message file ..
      - echo "CODEBUILD_INITIATOR:${CODEBUILD_INITIATOR}" | tee -a sns-message.txt
      - echo "CODEBUILD_BUILD_ID:${CODEBUILD_BUILD_ID}" | tee -a sns-message.txt
      - echo "CODEBUILD_SOURCE_REPO_URL:${CODEBUILD_SOURCE_REPO_URL}" | tee -a sns-message.txt
      - echo "CODEBUILD_SOURCE_VERSION:${CODEBUILD_SOURCE_VERSION}" | tee -a sns-message.txt
      - echo "CODEBUILD_RESOLVED_SOURCE_VERSION:${CODEBUILD_RESOLVED_SOURCE_VERSION}" | tee -a sns-message.txt
      - echo "DOCKER_COMPOSE_VERSION:${DOCKER_COMPOSE_VERSION}" | tee -a sns-message.txt
      - docker --version
      - echo  ******************************************************************************************************
  build:
    commands:
      - echo "Build started on `date`"
      - echo "LISTING THE REPOSITORIES"   
      - aws ecr describe-repositories
      - echo Building the DJANGO AND MYSQL DOCKER IMAGES !!!!
      - docker-compose build
      - docker image ls
#      - docker tag alpineimage:latest $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray_mysql:$DATETIME   
      - docker image ls
      - echo Logging.. in to Amazon ECR ...
      - eval $(aws ecr get-login --region $aws_default_region --no-include-email)
#      - docker push $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray_mysql:$DATETIME
      - echo  ******************************************************************************************************
         
  post_build:
    commands:

      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - echo  ******************************************************************************************************
