version: 0.2

phases:
  install:
    commands:
      - echo INSTALLING ECS_CLI
      - sudo curl -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
      - sudo chmod +x /usr/local/bin/ecs-cli
      - DATETIME=$(date +%d%m%y__%H%M)
      - VERSION="$(git log --pretty=format:'%h' -n 1) $(date +%d:%m:%Y*****%H:%M)"
      - echo $VERSION 
      - echo CONFIGURING ECS-CLI
      - ecs-cli configure --cluster $cluster_name --default-launch-type EC2 --region $aws_default_region --config-name $config_name
      - ecs-cli configure profile --profile-name $profile_name --access-key $aws_access_key_id --secret-key $aws_secret_access_key        
      - ecs-cli -v 
  pre_build:
    commands:
      - echo Logging.. in to Amazon ECR ...
      - pwd 
      - ls -l
      - eval $(aws ecr get-login --region $aws_default_region --no-include-email)
      - aws ecs list-container-instances --cluster $cluster_name
      - docker volume ls   
  build:
    commands: 
      - ecs-cli compose --verbose up --region $aws_default_region --cluster $cluster_name --launch-type EC2
      - ecs-cli ps 
  post_build:
    commands: 
