version: 0.2

phases:
  install:
    commands:

      - echo "Installing docker compose to run Docker compose UP"
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
  pre_build:
    commands:
      - echo " ******************************************************************************************************"
      - echo "Morning"
      - echo "Morning "
      - echo " ******************************************************************************************************"
  build:
    commands:
      - echo " ******************************************************************************************************"
      - echo "Build started on `date`"
      - echo "Building the Docker image.."      
      - echo " ******************************************************************************************************"
         
  post_build:
    commands:
      - echo " ******************************************************************************************************"
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - echo " ******************************************************************************************************"
