version: '2'

services:

  db:
    image: $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray_mysql:physhtray_mysql_v1
    volumes:
    - database:/var/lib/mysql  
    ports:
    - "9306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=phishtray
    networks:
    - webnet

  django:
    image: $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray:DjangoV2
    command: dockerize -wait tcp://db:3306 -timeout 60s bash -c "tail -f /dev/null"
    ports:
    - "9000:9000"
    - "9022:22"
    volumes:
    - $PWD:/usr/src/app
    networks:
    - webnet
    depends_on:
    - db

networks:
  webnet:

volumes:
  database:
  django:
