version: '2'

services:

  db:
    image: $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray_mysql:physhtray_mysql_v1
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - "9306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=phishtray
    networks:
    - webnet

  django:
    image: $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray:django_v1
    command: bash -c "python3.6 manage.py makemigrations; python3.6 manage.py migrate; python3.6 manage.py runserver 0:9000"
    ports:
    - "9000:9000"
    - "9022:22"
    volumes:
    - ./django:/usr/src/app
    networks:
    - webnet
    depends_on:
    - db

networks:
  webnet:
 
volumes:
  db: 
  django:
