version: '2'

services:

  db:
    image: $aws_account_id.dkr.ecr.$aws_default_region.amazonaws.com/phishtray_mysql:physhtray_mysql_v1
    volumes:
    - db:/var/lib/mysql
    ports:
    - "9306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=phishtray
    networks:
    - webnet



networks:
  webnet:
 
volumes:
  db: 
#  django:
