version: '3.3'

services:

  db:
    build:
      context: .
      cache_from:
        - $(${aws_account_id}.dkr.ecr.${aws_default_region}.amazonaws.com/phishtray_mysql:physhtray_mysql_v1)
#    image: ${aws_account_id}.dkr.ecr.${aws_default_region}.amazonaws.com/phishtray_mysql:physhtray_mysql_v1
    volumes:
    - ./db:/var/lib/mysql
    ports:
    - "9306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=phishtray
    networks:
    - webnet

  django: 
   build:
    context: .
      cache_from:
#        - ${{aws_account_id}.dkr.ecr.${aws_default_region}.amazonaws.com/phishtray:django_v1}
#    image: ${aws_account_id}.dkr.ecr.${aws_default_region}.amazonaws.com/phishtray:django_v1   
    command: dockerize -wait tcp://db:3306 -timeout 60s bash -c "python3.6 manage.py makemigrations; python3.6 manage.py migrate; tail -f /dev/null"
    ports:
    - "9000:9000"
    - "9022:22"
    volumes:
    - .:/usr/src/app
    networks:
    - webnet
    depends_on:
    - db

networks:
  webnet:
